language: c
compiler: 
    - gcc
os:
  - linux

addons:
    sources:
      - ubuntu-toolchain-r-test
    apt:
      packages:
        - gcc
        - libpcap0.8-dev
        - libpcap0.8	  

script: gcc -o monitor monitor.c -lpcap
